# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: IT Karl
logo:
email: itkarlit@gmail.com
description: Новости IT в текущей экономической системе.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://itkarl.ru"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
#theme: minima
permalink: pretty
paginate:  13
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  dtf:
    name:             DTF
    bio:              Это платформа для обсуждения игр, кино, разработки и технологий. У площадки нет консолидированной позиции, здесь собираются люди с разными мнениями и взглядами на одни и те же продукты развлекательной индустрии.
    gravatar:         https://avatars.mds.yandex.net/get-dialogs/1017510/b66dd0fb252ea39fa4fc/orig
    email:            play@dtf.ru
    website:          https://dtf.ru
  rbc:
    name:             РБК
    bio:              Ведущий мультимедийный холдинг России. Компания ведет операционную деятельность в сегментах интернет, телевидения и прессы. РБК – лидер среди новостных и бизнес-медиа, а также в сегменте регистрации доменов и хостинга. 
    gravatar:         https://s.rbk.ru/v10_rbcnews_static/common/current/images/logo.svg
    email:            letters@rbc.ru
    website:          https://www.rbc.ru/
